name: ci/cd

on:
  push:
    branches:
    - master
    - staging
    tags:
    - '*'

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      env:
        DOCKER_REGISTRY: docker.carbon.cc
        PROJECT_NAME: actions_project
        PROJECT_OWNER: jason_hord
      run: |
        shopt -s extglob

        case "${GITHUB_REF}" in
        */staging)
          VERSION="staging-${GITHUB_SHA}"
          echo "Using staging tagging rules: ${VERSION}"
          ;;

        */v+([0-9]).+([0-9]).+([0-9]))
          VERSION="$(echo ${GITHUB_REF} | cut -d '/' -f 3)"
          echo "Using release tagging rules: ${VERSION}"
          ;;

        *)
          echo "Ignoring ref (${GITHUB_REF}) with no tagging rules"
          exit 0
          ;;
        esac

        DOCKER_IMAGE="${DOCKER_REGISTRY}/${PROJECT_OWNER}/${PROJECT_NAME}:${VERSION}"
        echo "Docker image: ${DOCKER_IMAGE}"

        echo "Building container..."
        docker build \
          --file dockerfiles/main.dockerfile \
          --build-arg WORKING_DIRECTORY=/opt/"${PROJECT_OWNER}"/"${PROJECT_NAME}" \
          --tag "${DOCKER_IMAGE}" \
          .

        echo "Pushing image..."
